ones = ['one'...
        'two' ...
        'three' ...
        'four' ...
        'five' ...
        'six' ...
        'seven' ...
        'eight' ...
        'nine'];

tens = ['twenty'...
        'thirty'...
        'forty'...
        'fifty'...
        'sixty'...
        'seventy'...
        'eighty'...
        'ninety'];
    
irreg = ['ten'...
        'eleven'...
        'twelve'...
        'thirteen'...
        'fourteen'...
        'fifteen'...
        'sixteen'...
        'seventeen'...
        'eighteen'...
        'nineteen'];

hundreds = ['hundred'];

thousands = ['one' 'thousand'];

ands = ['and']

9*99*numel(ands)+numel(thousands)+900*numel(hundreds)+(10)*numel(irreg)...
+(100)*numel(tens)+(190)*numel(ones)
